### ISSUE TITLE
无法监测红包记录

### ISSUE THREAD

**Issue by liuxiriver** [qqqkoko123/qianghongbao#13]
在微信最新版测试发现，假如个人或聊天群发了红包，软件不会自动进入聊天详情页，需要手动点击进入，才会自动搜索点击红包。

**Comment by qqqkoko123** [comment]
不会啊，退到桌面，打开通知栏详情，自动会点开红包的，或者进入聊天窗口等待红包到来即可，不要在微信大厅里等红包，那样是不会有任何消息的

**Comment by liuxiriver** [comment]
主要检测通知状态栏微信的状态和聊天窗口的关键字对吧。懂了谢谢！
