### ISSUE TITLE
讲道理  为啥android11及以上的都不行 我都试过了

### ISSUE THREAD

**Issue by loper7** [qqqkoko123/qianghongbao#17]
讲道理  为啥android11及以上的都不行 我都试过了

**Comment by qqqkoko123** [comment]
我自己用的安卓11是可以的，应该是你哪里没设置对

**Comment by loperSeven** [comment]
无障碍  后台常驻 自启动 全都开了 找不到什么没设置对的  我是android12

**Comment by qqqkoko123** [comment]
重启无障碍服务

**Comment by loperSeven** [comment]
重启很多次了  甚至尝试过重启手机  微信版本 8.0.19

**Comment by qqqkoko123** [comment]
哦，微信版本又更新了？还没适配8.0.19哦

**Comment by qqqkoko123** [comment]
我看了，8.0.19是可以用的

**Comment by loperSeven** [comment]
那可能就是android12的不行吧

**Comment by qqqkoko123** [comment]
不应该啊，理论上是支持的，你是怎么抢的？在微信大厅？需要注意的是要进入微信聊天界面或者退到桌面打开通知详情才可以的哦

**Comment by loperSeven** [comment]
我是进入到具体的微信聊天界面的，至于退到桌面没试过，我用android11尝试了，一样的操作方式11确实可以，对了，我这是colorsOS 12

**Comment by s578868472** [comment]
华为的鸿蒙是不是不能抢呢

**Comment by qqqkoko123** [comment]
鸿蒙的，没真机测试

**Comment by s578868472** [comment]
> 鸿蒙的，没真机测试

好吧
