### ISSUE TITLE
使用遇到的问题请教

### ISSUE THREAD

**Issue by Norach-I** [qqqkoko123/qianghongbao#7]
请问启动运行后，必须进入一个群聊或者对话，才能实时识别检测嘛？停留在主界面，能否实时检测？测试了一下，停在主界面的时候，有[新红包]的字样显示时，并没有进去对应的群聊。。。。。。就来请教一下您

**Comment by qqqkoko123** [comment]
你是说微信吗？微信的话必须手机通知栏出现“微信红包”字样才会有“红包来了”智能播报以及点进去抢包

**Comment by Norach-I** [comment]
不是的，是QQ端。

**Comment by qqqkoko123** [comment]
QQ端的通知栏还没写，在新版中加进去

**Comment by Norach-I** [comment]
QQ版本是对的，但app内出现了权限被拒绝的字样，前往设置时也没看到具体是哪个权限。
![AH~9ES631EPWU)1@HJM T44](https://user-images.githubusercontent.com/51918042/147827647-b244c52f-ac39-4237-b265-bfcf6881821b.jpg)
![3S%UGLAA_PHL$XQQ()(`B9T](https://user-images.githubusercontent.com/51918042/147827651-e92305bd-5843-4069-b548-00b6d10a293f.jpg)

**Comment by qqqkoko123** [comment]
权限只要弹窗允许了就好了，手机里显示的仅仅是所有权限未被允许的，所以不需要管~

**Comment by Norach-I** [comment]
好的,感谢您~！
